// Generated by CoffeeScript 2.7.0
(function() {
  var Datastore, cleanStr, db, log;

  Datastore = require('nedb');

  log = console.log;

  db = null;

  this.createDB = function(path) {
    db = new Datastore({
      filename: path || './db/nedb.json',
      autoload: true
    });
    db.persistence.setAutocompactionInterval(120000);
    log("nedb loaded...");
    return db;
  };

  this.getDB = function() {
    return db;
  };

  cleanStr = function(str) {
    return str.trim().toLowerCase();
  };

  this.handler = function(db, opt) {
    return function(req, res, next) {
      var method;
      method = cleanStr(req.method);
      if (method === "get") {
        return db.find(req.body.query, function(err, docs) {
          if (err) {
            log(err);
            return res.send(404, "Server error.");
          } else {
            return res.send(200, docs);
          }
        });
      } else if (method === "head") {
        return db.count(req.body.query, function(err, count) {
          if (err) {
            log(err);
            return res.send(404, "Server error.");
          } else {
            return res.send(200, count);
          }
        });
      } else if (method === "post") {
        return db.insert(req.body.data, function(err, result) {
          if (err) {
            log(err);
            return res.send(404, "Server error.");
          } else {
            return res.send(200, result);
          }
        });
      } else if (method === "upsert") {
        return db.update(req.body.query, req.body.data, {
          upsert: true
        }, function(err, num, upsert) {
          if (err) {
            log(err);
            return res.send(404, "Server error.");
          } else {
            return res.send(200, {
              num: num,
              upsert: upsert
            });
          }
        });
      } else if (method === "all" || method === "put" || method === "update" || method === "patch") { //use put to do entire doc, use patch to update
        return db.update(req.body.query, req.body.data, {
          multi: true
        }, function(err, result) {
          if (err) {
            log(err);
            return res.send(404, "Server error.");
          } else {
            return res.send(200, result);
          }
        });
      } else if (method === "delete" || method === "remove" || method === "del") {
        return db.remove(req.body.query, {
          multi: !!req.body.multi
        }, function(err, num) {
          if (err) {
            log(err);
            return res.send(404, "Server error.");
          } else {
            db.persistence.compactDatafile();
            return res.send(200, num);
          }
        });
      } else if (method === "index") {
        return db.ensureIndex({
          fieldName: req.body.field
        }, function(err) {
          if (err) {
            log(err);
            return res.send(404, "Server error.");
          } else {
            return res.send(200, "OK");
          }
        });
      } else if (method === "uniqueindex") {
        return db.ensureIndex({
          fieldName: req.body.field,
          unique: true,
          sparse: true
        }, function(err) {
          if (err) {
            log(err);
            return res.send(404, "Server error.");
          } else {
            return res.send(200, "OK");
          }
        });
      } else if (method === "opt") { // other operations
        if (!!opt) {
          return opt(req, res, next, db);
        } else {
          return next(req, res);
        }
      } else {
        return next(req, res);
      }
    };
  };

}).call(this);
